/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as CheckoutPlanSlugRouteImport } from './routes/checkout.$planSlug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesServiceSlugRouteImport } from './routes/services.$serviceSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanSlugRoute = CheckoutPlanSlugRouteImport.update({
  id: '/$planSlug',
  path: '/$planSlug',
  getParentRoute: () => CheckoutRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/checkout/$planSlug': typeof CheckoutPlanSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/checkout/$planSlug': typeof CheckoutPlanSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/checkout/$planSlug': typeof CheckoutPlanSlugRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/services'
    | '/checkout/$planSlug'
    | '/services/$serviceSlug'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/checkout/$planSlug'
    | '/services/$serviceSlug'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/services'
    | '/checkout/$planSlug'
    | '/services/$serviceSlug'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planSlug': {
      id: '/checkout/$planSlug'
      path: '/$planSlug'
      fullPath: '/checkout/$planSlug'
      preLoaderRoute: typeof CheckoutPlanSlugRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$serviceSlug': {
      id: '/services/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutPlanSlugRoute: typeof CheckoutPlanSlugRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutPlanSlugRoute: CheckoutPlanSlugRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ServicesRouteChildren {
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
